# ~/.tmuxinator/project.yml

name: project
root: <%= @args[0] %>

pre: tp --json-projections-00 > a
# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
pre_window: pyenv activate neovim2
post: tmux ls | grep -v atta| cut -f 1 -d:| while read n; do tmux kill-session -t $n ;done

windows:
  - editor:
      layout: main-vertical
      panes:
        - pwd
        - pwd
  - work:

